service: vrp-app
image: mayur311002/vrp_new_app_appv11
registry:
  username: mayur311002
  password:
    - KAMAL_REGISTRY_PASSWORD
ssh:
  user: root
env:
  clear:
    POSTCODES_IO_URL: http://postcodes-service:8000
    OSRM_URL: http://osrm-service:5000
    STREAMLIT_SERVER_ADDRESS: 0.0.0.0
    STREAMLIT_BROWSER_SERVER_HEADLESS: true

servers:
  web:
    hosts:
      - 157.180.87.7
    options:
      publish: ["8501:8501"]  # Fixed: Changed 'ports' to 'publish'
      log-opt: max-size=10m
      memory: 2g  # Add memory limit
      memory-swap: 3g  # Add swap memory
      # Removed duplicate name/restart options
      # Kamal automatically handles these

accessories:
  osrm:
    image: mayur311002/vrp_new_app_osrm:latest-arm64
    host: 157.180.87.7
    port: "5000:5000"
    volumes:
      - /data/osrm:/data
    cmd: osrm-routed --algorithm mld /data/united-kingdom-latest.osrm
    options:
      name: osrm-service
      restart: unless-stopped
      log-opt: max-size=10m

  postcodes-app:
    image: mayur311002/vrp_new_app_postcodes_app:latest-arm64-v54
    host: 157.180.87.7
    port: "8000:8000"
    env:
      clear:
        PGHOST: postcodes-db
        PGPORT: 5432
        PGUSER: postcodesio
        PGDATABASE: postcodesio
      secret:
        - PGPASSWORD
        - POSTGRES_PASSWORD
        - DATABASE_URL
    volumes:
      - /data/postcodes:/data
    options:
      name: postcodes-service
      restart: unless-stopped

  postcodes-db:
    image: mayur311002/vrp_postgis:15-alpine-v6
    host: 157.180.87.7
    env:
      clear:
        POSTGRES_USER: postcodesio
        POSTGRES_DB: postcodesio
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    options:
      name: postcodes-db
      restart: unless-stopped

builder:
  arch: arm64
proxy:
  app_port: 8501
  
