# VRP_new_app/config/deploy.yml
service: vrp-app
image: mayur311002/vrp_new_app_app-arm64
servers:
  - 157.180.87.7
registry:
  username: mayur311002
  password:
    - KAMAL_REGISTRY_PASSWORD
ssh:
  user: root
env:
  clear:
    POSTCODES_IO_URL: http://postcodes-app:8000
    OSRM_URL: http://osrm:5000
    STREAMLIT_SERVER_ADDRESS: 0.0.0.0
    STREAMLIT_SERVER_PORT: 8501
    STREAMLIT_BROWSER_SERVER_HEADLESS: true
    STREAMLIT_SERVER_ENABLE_CORS: false  # Added for security

# Health check configuration for Streamlit
healthcheck:
  path: /_stcore/health  # Streamlit's built-in health endpoint
  port: 8501
  interval: 10s
  timeout: 5s
  retries: 3

# Network configuration
networks:
  - kamal
  - vrp-network  # Connect to accessory network

# Traefik configuration for proper routing
traefik:
  args:
    wait: 60s  # Increased timeout for health checks
    publish:
      - "8501:8501"
  labels:
    traefik.http.routers.vrp-app.rule: PathPrefix(`/`)
    traefik.http.services.vrp-app.loadbalancer.healthcheck.path: /_stcore/health

accessories:
  osrm:
    image: mayur311002/vrp_new_app_osrm:latest-arm64
    host: 157.180.87.7
    port: "5000:5000"
    network: vrp-network
    volumes:
      - /data/osrm:/data
    cmd: osrm-routed --algorithm mld /data/united-kingdom-latest.osrm
    healthcheck:  # Added health check for OSRM
      test: ["CMD", "curl", "-f", "http://localhost:5000/route/v1/driving/13.388860,52.517037;13.397634,52.529407?overview=false"]
      interval: 30s
      timeout: 5s
      retries: 3

  postcodes-db:
    image: idealpostcodes/postcodes.io.db:latest
    host: 157.180.87.7
    port: "5432:5432"
    env:
      clear:
        POSTGRES_USER: postcodesio
        POSTGRES_DATABASE: postcodesio
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    network: vrp-network
    healthcheck:  # Added health check for Postgres
      test: ["CMD-SHELL", "pg_isready -U postcodesio"]
      interval: 10s
      timeout: 5s
      retries: 5

  postcodes-app:
    image: mayur311002/vrp_new_app_postcodes_app:latest-arm64
    host: 157.180.87.7
    port: "8000:8000"
    network: vrp-network
    env:
      clear:
        DATABASE_URL: postgresql://postcodesio:${POSTGRES_PASSWORD}@postcodes-db:5432/postcodesio
      secret:
        - POSTGRES_PASSWORD
    healthcheck:  # Added health check for Postcodes API
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 15s
      timeout: 5s
      retries: 3

builder:
  arch: arm64

# Optional: Add resource constraints
container:
  memory: 2g
  cpus: 1.5
