service: vrp-app
image: mayur311002/vrp_new_app_app-arm64:latest
servers:
  - 157.180.87.7
network: vrp-network
registry:
  username: mayur311002
  password:
    - KAMAL_REGISTRY_PASSWORD
ssh:
  user: root
env:
  clear:
    POSTCODES_IO_URL: http://postcodes-app:8000
    OSRM_URL: http://osrm:5000
    STREAMLIT_SERVER_ADDRESS: 0.0.0.0
    STREAMLIT_SERVER_PORT: 8501
    STREAMLIT_BROWSER_SERVER_HEADLESS: true
    STREAMLIT_SERVER_ENABLE_CORS: false
labels:
  traefik.enable: true
  traefik.http.routers.vrp-app.rule: PathPrefix(`/_stcore`)
  traefik.http.routers.vrp-app.entrypoints: web
  traefik.http.services.vrp-app.loadbalancer.server.port: 8501
  traefik.http.services.vrp-app.loadbalancer.healthcheck.path: /_stcore/health
  traefik.http.services.vrp-app.loadbalancer.healthcheck.interval: 5s
  traefik.http.services.vrp-app.loadbalancer.healthcheck.timeout: 3s
  traefik.http.services.vrp-app.loadbalancer.healthcheck.retries: 3
accessories:
  osrm:
    image: mayur311002/vrp_new_app_osrm:latest-arm64
    host: 157.180.87.7
    port: "5000:5000"
    network: vrp-network
    volumes:
      - /data/osrm:/data
    cmd: "/usr/local/bin/osrm-routed --algorithm=mld /data/united-kingdom-latest.osrm"
  postcodes:
    image: idealpostcodes/postcodes.io.db:latest
    host: 157.180.87.7
    port: "5432:5432"
    env:
      clear:
        POSTGRES_USER: postcodesio
        POSTGRES_DB: postcodesio
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    network: vrp-network
  postcodes-app:
    image: mayur311002/vrp_new_app_postcodes:latest-arm64
    host: 157.180.87.7
    port: "8000:8000"
    env:
      clear:
        DATABASE_URL: postgres://postcodesio:${POSTGRES_PASSWORD}@postcodes:5432/postcodesio
      secret:
        - POSTGRES_PASSWORD
    network: vrp-network
builder:
  arch: arm64
