# VRP_new_app/config/deploy.yml
service: vrp-app
image: mayur311002/vrp_new_app_app-arm64
servers:
  - 157.180.87.7
registry:
  username: mayur311002
  password:
    - KAMAL_REGISTRY_PASSWORD
ssh:
  user: root
env:
  clear:
    POSTCODES_IO_URL: http://postcodes-app:8000
    OSRM_URL: http://osrm:5000
    STREAMLIT_SERVER_ADDRESS: 0.0.0.0
    STREAMLIT_SERVER_PORT: 8501
    STREAMLIT_BROWSER_SERVER_HEADLESS: true
    STREAMLIT_SERVER_ENABLE_CORS: false

# Health check configuration (old format)
healthcheck:
  path: /_stcore/health
  port: 8501

# Add network connections through labels
labels:
  service: vrp-app
  network: vrp-network

# Traefik configuration through options
options:
  publish: "8501:8501"
  network: "kamal,vrp-network"

accessories:
  osrm:
    image: mayur311002/vrp_new_app_osrm:latest-arm64
    host: 157.180.87.7
    port: "5000:5000"
    files:
      - /data/osrm:/data
    cmd: osrm-routed --algorithm mld /data/united-kingdom-latest.osrm
    options:
      network: vrp-network

  postcodes-db:
    image: idealpostcodes/postcodes.io.db:latest
    host: 157.180.87.7
    port: "5432:5432"
    env:
      clear:
        POSTGRES_USER: postcodesio
        POSTGRES_DATABASE: postcodesio
      secret:
        - POSTGRES_PASSWORD
    files:
      - /data/postgres:/var/lib/postgresql/data
    options:
      network: vrp-network

  postcodes-app:
    image: mayur311002/vrp_new_app_postcodes_app:latest-arm64
    host: 157.180.87.7
    port: "8000:8000"
    env:
      clear:
        DATABASE_URL: postgresql://postcodesio:${POSTGRES_PASSWORD}@postcodes-db:5432/postcodesio
      secret:
        - POSTGRES_PASSWORD
    options:
      network: vrp-network

builder:
  arch: arm64
