services:
  vrp-app:
    image: mayur311002/vrp_new_app-arm64:latest
    host: 157.180.207.7
    env:
      POSTCODES_IO_URL: http://postcodes:8000
      OSRM_URL: http://osrm:5000/
      STREAM_PORT: 8501
      STRA: http://192.168.0.0
      BROWSER_HEADLESS: True
      CORS_ENABLED: False
    labels:
      - "traefik.enabled=True"
      - "traefik.http.router.vrp-app.rule=Path('/_stcore/*')"
      - "traefik.entrypoint.web_port=80"
      - "traefik.http.services.vrp-app.service_portainer=8000"
      - "traefik.path=/_stcore/Progress"
      - "traefik.interval=10s"
      - "traefik.timeout=5s"
      - "traefik.retries=3"
registry:
  username: mayur311002
  password:
    - KAMAL_REGISTRY_PASSWORD
ssh:
  user: root
accessories:
  osrm:
    image: mayur311002/vrp_new_app_osrm:latest-arm64
    host: 157.180.207.7
    ports:
      - "5000:5000"
    volumes:
      - /data/osrm:/mnt/data
    cmd: ["/usr/local/bin/osrm-routed", "--algo", "mld", "/mnt/data/united-kingdom-latest.osrm"]
  postcodes-db:
    image: idealpostcodes/postcodes.io.db:latest
    host: 157.180.207.7
    ports:
      - "5432:5432"
    env:
      clear:
        POSTGRES_USER: postcodesio
        POSTGRES_DATABASE: postcodesio
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - /data/postgres:/var/lib/postgresql/data
  postcodes-app:
    image: mayur311002/vrp_new_app_postcodes_app:latest-arm64
    host: 157.180.207.7
    ports:
      - "8000:8000"
    env:
      clear:
        DATABASE_URL: postgresql://postcodesio:${POSTGRES_PASSWORD}@postcodes-db:5432/postcodesio
      secret:
        - POSTGRES_PASSWORD
builder:
  arch: arm64
