service: vrp-app
image: mayur311002/vrp_new_app_app:latest
servers:
  - 157.180.87.7
registry:
  username: mayur311002
  password:
    - KAMAL_REGISTRY_PASSWORD
ssh:
  user: root
env:
  clear:
    POSTCODES_IO_URL: http://postcodes-app:8000
    OSRM_URL: http://osrm:5000  # Add this critical environment variable
    STREAMLIT_SERVER_ADDRESS: 0.0.0.0
    STREAMLIT_SERVER_PORT: 8501
    STREAMLIT_BROWSER_SERVER_HEADLESS: true
accessories:
  osrm:
    image: mayur311002/vrp_new_app_osrm:latest-arm64
    host: 157.180.87.7
    port: "5000:5000"
    network: vrp-network
    volumes:  # Add persistent volume for map data
      - /data/osrm:/data
    cmd: osrm-routed --algorithm mld /data/united-kingdom-latest.osrm

  postcodes-db:
    image: idealpostcodes/postcodes.io.db:latest
    host: 157.180.87.7
    port: "5432:5432"
    env:
      clear:
        POSTGRES_USER: postcodesio
        POSTGRES_DATABASE: postcodesio
      secret:
        - POSTGRES_PASSWORD
    volumes:  # Add persistent volume for database
      - /data/postgres:/var/lib/postgresql/data
    network: vrp-network

  postcodes-app:
    image: mayur311002/vrp_new_app_postcodes_app:latest-arm64
    host: 157.180.87.7
    port: "8000:8000"
    env:
      clear:
        POSTGRES_HOST: postcodes-db  # Use service name for internal DNS
        POSTGRES_USER: postcodesio
        POSTGRES_DATABASE: postcodesio
      secret:
        - POSTGRES_PASSWORD
    depends_on:  # Add dependency
      - postcodes-db
    network: vrp-network
builder:
  arch: arm64
