# Kamal 2.6.1 configuration for deploying vrp-app and accessories
service: vrp-app
image: mayur311002/vrp_new_app_app:arm64
version: arm64
servers:
  - 157.180.87.7
registry:
  username: mayur311002
  password:
    - KAMAL_REGISTRY_PASSWORD
ssh:
  user: root
env:
  clear:
    POSTCODES_IO_URL: http://postcodes-app:8000
    STREAMLIT_BROWSER_SERVER_ADDRESS: localhost
    STREAMLIT_SERVER_ADDRESS: 0.0.0.0
    STREAMLIT_SERVER_PORT: 8501
    STREAMLIT_BROWSER_SERVER_HEADLESS: true
accessories:
  osrm:
    image: mayur311002/vrp_new_app_osrm:arm64
    host: 157.180.87.7
    port: 5000
  postcodes-db:
    image: idealpostcodes/postcodes.io.db:latest
    host: 157.180.87.7
    port: 5432
    env:
      clear:
        POSTGRES_USER: postcodesio
        POSTGRES_DATABASE: postcodesio
      secret:
        - POSTGRES_PASSWORD
  postcodes-app:
    image: mayur311002/vrp_new_app_postcodes_app:arm64
    host: 157.180.87.7
    port: 8000
    env:
      clear:
        POSTGRES_HOST: postcodes-db
        POSTGRES_USER: postcodesio
        POSTGRES_DATABASE: postcodesio
      secret:
        - POSTGRES_PASSWORD
builder:
  arch: arm64
