#VRP_new_app/config/deploy.yml
service: vrp-app
image: mayur311002/vrp_new_app_app
servers:
  - 157.180.87.7
registry:
  username: mayur311002
  password:
    - KAMAL_REGISTRY_PASSWORD
ssh:
  user: root
env:
  clear:
    POSTCODES_IO_URL: http://postcodes-app:8000
    STREAMLIT_SERVER_ADDRESS: 0.0.0.0
    STREAMLIT_SERVER_PORT: 8501
    STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
    KAMAL_HEALTH_CHECK_PATH: "/_stcore/health"
    KAMAL_CONTAINER_PORT: "8501"
# Add this traefik section to specify the port
traefik:
  args:
    publish: "8501:8501"  # Map host port 8501 to container port 8501
accessories:
  osrm:
    image: mayur311002/vrp_new_app_osrm:arm64
    host: 157.180.87.7
    port: "5000:5000"
  postcodes-db:
    image: idealpostcodes/postcodes.io.db:latest
    host: 157.180.87.7
    port: "5432:5432"
    env:
      clear:
        POSTGRES_USER: postcodesio
        POSTGRES_DATABASE: postcodesio
      secret:
        - POSTGRES_PASSWORD
  postcodes-app:
    image: mayur311002/vrp_new_app_postcodes_app:arm64
    host: 157.180.87.7
    port: "8000:8000"
    env:
      clear:
        POSTGRES_HOST: postcodes-db
        POSTGRES_USER: postcodesio
        POSTGRES_DATABASE: postcodesio
      secret:
        - POSTGRES_PASSWORD
builder:
  arch: arm64
