service: vrp-app
image: mayur311002/vrp_new_app-arm64:latest
servers:
  - 157.180.207.35
registry:
  username: mayur311002
  password:
    secret:
      - KAMAL_REGISTRY_PASSWORD
ssh:
  user: root
env:
  clear:
    POSTCODES_IO_URL: http://postcodes-app:8000
    OSRM_URL: http://osrm-routed:5000
    STREAMLIT_PORT: 8501
    STREAMLITER_ADDRESS: 127.0.0.1
    BROWSER_HEADLESS: True
    CORS_ENABLED: False
labels:
  traefik_enabled: True
  traefik_router_rule: PathPrefix=/_stcore/
  traefik_entrypoint: Web
  traefik_service_port: 8501
  health_check_path: /healthz/
  health_check_interval: 10s
  health_check_timeout: 5s
  health_check_retries: 3
accessories:
  osrm:
    image: osrm/osrm-backend:latest
    host: localhost
    port: 8000
    volumes:
      - /data/osrm:/mnt/data
    cmd: /usr/local/bin/osrm-routed --algo=mld /mnt/data/osrm
  postcodes:
    image: postgres:latest
    host: localhost
    port: 5432
    env:
      POSTGRES_USER: postcodesio
      POSTGRES_DB: postcodes
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - /data/postgres:/var/lib/postgres/data
  postcodes-app:
    image: mayur311002/vrp_new_app_postcodes:latest-arm64
    host: localhost
    port: 8080
    env:
      DATABASE_URL: postgres://postcodesio:${POSTGRES_PASSWORD}@postcodes:5432/postcodes
      secret:
        - POSTGRES_PASSWORD
builder:
  arch: arm64
