service: vrp-app
image: mayur311002/vrp_new_app_app-arm64
servers:
  - 157.180.87.7

registry:
  username: mayur311002
  password:
    - KAMAL_REGISTRY_PASSWORD
ssh:
  user: root
env:
  clear:
    POSTCODES_IO_URL: http://postcodes-app:8000
    OSRM_URL: http://osrm:5000
    STREAMLIT_SERVER_ADDRESS: 0.0.0.0
    STREAMLIT_BROWSER_SERVER_HEADLESS: true

accessories:
  osrm:
    image: mayur311002/vrp_new_app_osrm:latest-arm64
    host: 157.180.87.7
    port: "5000:5000"
    network: kamal
    volumes:
      - /data/osrm:/data
    cmd: osrm-routed --algorithm mld /data/united-kingdom-latest.osrm
    # Add health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/route/v1/driving/-0.085,51.516;-0.09,51.51"]
      interval: 30s
      timeout: 10s
      retries: 5

  postcodes-db:
    image: idealpostcodes/postcodes.io.db:latest
    host: 157.180.87.7
    network: kamal
    env:
      clear:
        POSTGRES_USER: postcodesio
        POSTGRES_DATABASE: postcodesio
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    # Add health check
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postcodesio -d postcodesio"]
      interval: 10s
      timeout: 5s
      retries: 5

  postcodes-app:
    image: mayur311002/vrp_new_app_postcodes_app:latest-arm64
    host: 157.180.87.7
    network: kamal
    env:
      clear:
        DATABASE_URL: postgresql://postcodesio:${POSTGRES_PASSWORD}@postcodes-db:5432/postcodesio
      secret:
        - POSTGRES_PASSWORD
    # Add health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5

builder:
  arch: arm64
