services:
  osrm:
    build: ./osrm
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf 'http://localhost:5000/route/v1/driving/-2.0,54.0;-1.9,54.1' > /dev/null || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 20
      start_period: 300s
    volumes:
      - ./osrm:/data
    command: osrm-routed --algorithm mld /data/united-kingdom-latest.osrm

  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      osrm:
        condition: service_healthy
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_SERVER_ADDRESS=localhost

volumes:
  osrm-data: