services:
  osrm:
    build: ./osrm
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf 'http://localhost:5000/route/v1/driving/-2.0,54.0;-1.9,54.1' > /dev/null || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 20
      start_period: 300s
    volumes:
      - ./osrm:/data
    command: osrm-routed --algorithm mld /data/united-kingdom-latest.osrm

  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      osrm:
        condition: service_healthy
      postcodes-app:
        condition: service_healthy
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_SERVER_ADDRESS=localhost
      - POSTCODES_IO_URL=http://postcodes-app:8000

  postcodes-db:
    image: idealpostcodes/postcodes.io.db
    environment:
      - POSTGRES_USER=postcodesio
      - POSTGRES_PASSWORD= # Replace with your password
      - POSTGRES_DB=postcodesio
    volumes:
      - postcodes-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postcodesio"]
      interval: 10s
      timeout: 5s
      retries: 5

  postcodes-app:
    build:
      context: ./postcodes-app
      dockerfile: Dockerfile
    depends_on:
      postcodes-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postcodesio:# Replace with your password@postcodes-db:5432/postcodesio
      - LOG_LEVEL=trace
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 60s

volumes:
  osrm-data:
  postcodes-data:
